{
  config,
  lib,
  pkgs,
  namespace,
  ...
}:
with lib;
with lib.${namespace};
let
  cfg = config.${namespace}.services.ente-server;
  sopsCfg = config.${namespace}.system.sops;
in
{
  options.${namespace}.services.ente-server = {
    enable = mkEnableOption "native Ente Auth backend server";

    package = mkOption {
      description = "The Ente server package to run.";
      type = types.package;
      default = pkgs.${namespace}.ente-server;
    };

    domain = mkOption {
      description = "Public domain of the Ente Auth frontend and backend.";
      type = types.str;
      default = "ente.stahl.sh";
    };

    port = mkOption {
      description = "Local TCP port the Ente server listens on.";
      type = types.port;
      default = 6789;
    };

    secretsFile = mkOption {
      description = "SOPS file containing the Ente server secrets.";
      type = types.path;
      default = sopsCfg.secretsDir + "/blarm-ente-server.yaml";
    };

    credentialsFile = mkOption {
      description = "Rendered Ente server credentials YAML file.";
      type = types.str;
      readOnly = true;
      default = config.sops.templates."ente-server-credentials.yaml".path;
    };

    dataDir = mkOption {
      description = "Persistent state directory for the Ente server.";
      type = types.path;
      default = "/data/ente";
    };

    database = {
      name = mkOption {
        description = "PostgreSQL database name for Ente.";
        type = types.str;
        default = "ente";
      };

      user = mkOption {
        description = "PostgreSQL user for Ente. This must match the systemd service user for peer auth.";
        type = types.str;
        default = "ente";
      };
    };

    nginx = {
      enable = mkEnabledOption "Enable nginx reverse proxy for Ente server.";
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.database.name == cfg.database.user;
        message = "awesome-flake.services.ente-server.database.name must match database.user because PostgreSQL ensureDBOwnership requires a database with the same name as the owner.";
      }
    ];

    ${namespace} = {
      system.sops = enabled;
      services.acme.enable = mkIf cfg.nginx.enable true;
    };

    sops.secrets = {
      "ente-server/key/encryption" = {
        format = "yaml";
        key = "ente/key/encryption";
        sopsFile = cfg.secretsFile;
      };
      "ente-server/key/hash" = {
        format = "yaml";
        key = "ente/key/hash";
        sopsFile = cfg.secretsFile;
      };
      "ente-server/jwt/secret" = {
        format = "yaml";
        key = "ente/jwt/secret";
        sopsFile = cfg.secretsFile;
      };
    };

    sops.templates."ente-server-credentials.yaml" = {
      owner = cfg.database.user;
      group = "ente";
      mode = "0400";
      restartUnits = [ "ente-server.service" ];
      content = ''
        # Generated by sops-nix. Do not edit manually.
        # For Ente Auth only, no S3 section is required.
        http:
          use-tls: false
          port: ${toString cfg.port}

        db:
          # lib/pq treats an absolute host path as a PostgreSQL Unix socket directory.
          host: /run/postgresql
          port: 5432
          name: ${cfg.database.name}
          user: ${cfg.database.user}
          password: ""
          sslmode: disable

        apps:
          accounts: https://${cfg.domain}

        key:
          encryption: ${config.sops.placeholder."ente-server/key/encryption"}
          hash: ${config.sops.placeholder."ente-server/key/hash"}

        jwt:
          secret: ${config.sops.placeholder."ente-server/jwt/secret"}
      '';
    };

    networking.firewall.allowedTCPPorts = mkIf cfg.nginx.enable [
      80
      443
    ];

    users.groups.ente = { };
    users.users.${cfg.database.user} = {
      isSystemUser = true;
      group = "ente";
    };

    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir} 0700 ${cfg.database.user} ente -"
    ];

    services.postgresql = {
      enable = true;
      ensureDatabases = [ cfg.database.name ];
      ensureUsers = [
        {
          name = cfg.database.user;
          ensureDBOwnership = true;
        }
      ];
    };

    systemd.services.ente-server = {
      description = "Ente Auth backend server";
      after = [
        "postgresql.service"
        "postgresql-setup.service"
      ];
      requires = [ "postgresql.service" ];
      wantedBy = [ "multi-user.target" ];

      environment = {
        ENVIRONMENT = "local";
        ENTE_CREDENTIALS_FILE = cfg.credentialsFile;
        GIN_MODE = "release";
      };

      serviceConfig = {
        ExecStart = "${cfg.package}/bin/museum";
        ExecStartPre = "${pkgs.coreutils}/bin/test -r ${lib.escapeShellArg cfg.credentialsFile}";
        User = cfg.database.user;
        Group = "ente";
        WorkingDirectory = "${cfg.package}/share/ente-server";
        Restart = "on-failure";
        RestartSec = "10s";

        CapabilityBoundingSet = "";
        DevicePolicy = "closed";
        LockPersonality = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateTmp = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectProc = "invisible";
        ProtectSystem = "strict";
        ReadWritePaths = [ cfg.dataDir ];
        RestrictAddressFamilies = [
          "AF_INET"
          "AF_INET6"
          "AF_UNIX"
        ];
        RestrictNamespaces = true;
        RestrictRealtime = true;
        SystemCallArchitectures = "native";
        UMask = "0077";
      };
    };

    services.nginx = mkIf cfg.nginx.enable {
      enable = true;
      virtualHosts."${cfg.domain}" = {
        locations = {
          "/api".return = "301 /api/";
          "/api/" = {
            proxyPass = "http://127.0.0.1:${toString cfg.port}/";
            recommendedProxySettings = true;
          };
        };
      };
    };
  };
}
