# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/1616e34a-a8c6-4e18-882c-d955b4f8ffeb";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/24243112-bae6-4842-af26-4db18f8afc3f";
    fsType = "btrfs";
    options = [ "rw,relatime,ssd,space_cache=v2,subvol=root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/24243112-bae6-4842-af26-4db18f8afc3f";
    fsType = "btrfs";
    options = [ "rw,relatime,ssd,space_cache=v2,subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/24243112-bae6-4842-af26-4db18f8afc3f";
    fsType = "btrfs";
    options = [ "rw,relatime,ssd,space_cache=v2,subvol=nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/24243112-bae6-4842-af26-4db18f8afc3f";
    fsType = "btrfs";
    options = [ "rw,relatime,ssd,space_cache=v2,subvol=log" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/24243112-bae6-4842-af26-4db18f8afc3f";
    fsType = "btrfs";
    options = [ "rw,relatime,ssd,space_cache=v2,subvol=persist" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DF1D-1330";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/data/ssd" = {
    device = "/dev/mapper/ssd";
    fsType = "btrfs";
    options = [ "rw,relatime,ssd,space_cache=v2,nofail" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp36s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
